package com.example.flagquizgame
object MyData {
    var arrayList = ArrayList<Flag>()
        fun getArray(i: Int): ArrayList<Flag> {
            when (i) {
                0 -> arrayList = asia()
                1-> arrayList = europe()
                2-> arrayList = northAmerica()
                3-> arrayList = southAmerica()
                4-> arrayList = Africa()
                5-> arrayList = Australia()
            }
        return arrayList }
    private fun Australia(): ArrayList<Flag>{
        arrayList.add(Flag("Australia", R.drawable.australia))
        arrayList.add(Flag("NewGuinea", R.drawable.papuanewginea))
        arrayList.add(Flag("NewZealand", R.drawable.newzealand))
        arrayList.add(Flag("Fiji", R.drawable.fiji))
        arrayList.shuffle()
        return arrayList }
    private fun Africa(): ArrayList<Flag> {
        arrayList.add(Flag("Nigeria", R.drawable.nigeria))
        arrayList.add(Flag("Ethiopia", R.drawable.ethiopia))
        arrayList.add(Flag("Egypt", R.drawable.egypt))
        arrayList.add(Flag("DRCong", R.drawable.drcongo))
        arrayList.add(Flag("Tanzania", R.drawable.tanzania))
        arrayList.add(Flag("SouthAfrica", R.drawable.southafrica))
        arrayList.add(Flag("Kenya", R.drawable.kenya))
        arrayList.add(Flag("Uganda", R.drawable.uganda))
        arrayList.add(Flag("Algeria", R.drawable.algeria))
        arrayList.shuffle()
        return arrayList }
    private fun southAmerica(): ArrayList<Flag> {
        arrayList.add(Flag("Brazil", R.drawable.brazil))
        arrayList.add(Flag("Colombia", R.drawable.colombia))
        arrayList.add(Flag("Argentina", R.drawable.argentina))
        arrayList.add(Flag("Peru", R.drawable.peru))
        arrayList.add(Flag("Venezuela", R.drawable.venezuela))
        arrayList.add(Flag("Chile", R.drawable.chila))
        arrayList.add(Flag("Ecuador", R.drawable.ecuador))
        arrayList.add(Flag("Bolivia", R.drawable.boliva))
        arrayList.add(Flag("Paraguay", R.drawable.paraguay))
        arrayList.add(Flag("Uruguay", R.drawable.uruguay))
        arrayList.add(Flag("Guyana", R.drawable.guyana))
        arrayList.add(Flag("Suriname", R.drawable.suriname))
        arrayList.add(Flag("FrenchGuiana", R.drawable.frenchguiana))
        arrayList.shuffle()
        return arrayList }
    private fun northAmerica(): ArrayList<Flag> {
        arrayList.add(Flag("Mexico", R.drawable.mexico))
        arrayList.add(Flag("Canada", R.drawable.canada))
        arrayList.add(Flag("Guatemala", R.drawable.guatemala))
        arrayList.add(Flag("Haiti", R.drawable.haiti))
        arrayList.add(Flag("Cuba", R.drawable.cuba))
        arrayList.add(Flag("Honduras", R.drawable.honduras))
        arrayList.add(Flag("Nicaragua", R.drawable.nicaragua))
        arrayList.add(Flag("ElSalvador", R.drawable.elsalvador))
        arrayList.add(Flag("CostaRica", R.drawable.costarica))
        arrayList.shuffle()
        return arrayList }
    private fun europe(): ArrayList<Flag> {
        arrayList.add(Flag("Germany", R.drawable.germany))
        arrayList.add(Flag("UK", R.drawable.unitedkingdom))
        arrayList.add(Flag("France", R.drawable.france))
        arrayList.add(Flag("Italy", R.drawable.italy))
        arrayList.add(Flag("Spain", R.drawable.spain))
        arrayList.add(Flag("Ukraine", R.drawable.ukraine))
        arrayList.add(Flag("Poland", R.drawable.poland))
        arrayList.add(Flag("Romania", R.drawable.romania))
        arrayList.add(Flag("Netherlands", R.drawable.netherlands))
        arrayList.add(Flag("Belgium", R.drawable.belgium))
        arrayList.add(Flag("Greece", R.drawable.greece))
        arrayList.add(Flag("Portugal", R.drawable.portugal))
        arrayList.add(Flag("Sweden", R.drawable.sweden))
        arrayList.add(Flag("Hungary", R.drawable.hungary))
        arrayList.add(Flag("Ireland", R.drawable.ireland))
        arrayList.add(Flag("Austria", R.drawable.austria))
        arrayList.add(Flag("Serbia", R.drawable.serbia))
        arrayList.add(Flag("Finland", R.drawable.finland))
        arrayList.add(Flag("Monaco", R.drawable.monaco))
        arrayList.shuffle()
        return arrayList }
    private fun asia(): ArrayList<Flag> {
        arrayList.add(Flag("India", R.drawable.india))
        arrayList.add(Flag("Indonesia", R.drawable.indonesia))
        arrayList.add(Flag("Pakistan", R.drawable.pakistan))
        arrayList.add(Flag("Bangladesh", R.drawable.bangladesh))
        arrayList.add(Flag("Japan", R.drawable.japan))
        arrayList.add(Flag("Philippines", R.drawable.phillipines))
        arrayList.add(Flag("Vietnam", R.drawable.vietnam))
        arrayList.add(Flag("Turkey", R.drawable.turkey))
        arrayList.add(Flag("Iran", R.drawable.iran))
        arrayList.add(Flag("Thailand", R.drawable.thailand))
        arrayList.add(Flag("Myanmar", R.drawable.myanmar))
        arrayList.add(Flag("SouthKorea", R.drawable.southkorea))
        arrayList.add(Flag("Iraq", R.drawable.iraq))
        arrayList.add(Flag("Afghanistan", R.drawable.afghanistan))
        arrayList.add(Flag("SaudiArabia", R.drawable.saudiarabia))
        arrayList.add(Flag("Malaysia", R.drawable.malaysia))
        arrayList.add(Flag("Yemen", R.drawable.yemen))
        arrayList.add(Flag("Nepal", R.drawable.nepal))
        arrayList.add(Flag("NorthKorea", R.drawable.northkorea))
        arrayList.add(Flag("SriLanka", R.drawable.srilanka))
        arrayList.add(Flag("Kazakhstan", R.drawable.kazakhstan))
        arrayList.add(Flag("Syria", R.drawable.syria))
        arrayList.add(Flag("Cambodia", R.drawable.cambodia))
        arrayList.add(Flag("Jordan", R.drawable.jordan))
        arrayList.add(Flag("Azerbaijan", R.drawable.azerbaijan))
        arrayList.add(Flag("ArabEmirates", R.drawable.unitedarabemirates))
        arrayList.add(Flag("Tajikistan", R.drawable.tajikistan))
        arrayList.add(Flag("Qatar", R.drawable.qatar))
        arrayList.add(Flag("Kyrgyzstan", R.drawable.kyrgyzstan))
        arrayList.add(Flag("Turkmenistan", R.drawable.turkmenistan))
        arrayList.shuffle()
        return arrayList }
}